handle failed test in assemble script

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -83,8 +83,14 @@ else
     echo "---> running api test"
     cd api
     npm test
+    if [ $? -eq 0 ]; then
+        echo " ---> Success: API TESTS PASSED"
+    else
+        echo " ---> Failure: API TESTS FAILED"
+        exit 1
+    fi
     cd ..
-    
+
 
 	#do not fail when there is no build script
 	echo "---> Building in production mode"
